### ISSUE TITLE
How should we handle versioning of the db?

### ISSUE THREAD

**Issue by capttrousers** [ddgll/vue-idb#6]
Dexie allows you to update the version number, modify the stores/schemsas, and then call the update method if necessary. 

http://dexie.org/docs/Version/Version

How should we handle upgrading our database with vue-idb?

**Comment by ddgll** [comment]
Hello, you'll be able to do that in next version =)

**Comment by ddgll** [comment]
Done =)

**Comment by capttrousers** [comment]
if I modify the schemas or version number I get this error:

```
index.js:1 A IndexedDB error occured DexieError {_e: Error
    at getErrorWithStack (eval at <anonymous> (http://localhost:4000/client.js:986:1), <anonym…, name: "UpgradeError", message: "Dexie specification of currently installed DB version is missing", inner: null, 

...

    at getErrorWithStack (eval at <anonymous> (http://localhost:4000/client.js:986:1), <anonym…, name: "OpenFailedError", message: "UpgradeError Dexie specification of currently installed DB version is missing", inner: DexieError, _promise: Promise, …}
```

**Comment by capttrousers** [comment]
How should we handle upgrading the schema with a bump in version number?

**Comment by tartinesKiller** [comment]
Same problem here, even after the latest commit (BUGFIX on adding schemas on existing DB UPDATES dependencies #32) dbe43f7e77bdbacf6a4dc4eebd270131fd601542
Made a quick n' dirty fork allowing to pass an array of versions at VueIdb constructor, waiting for @ddgll to add his way to add new schemas to the doc. Thanks in advance, and thanks for this useful wrapper ;) 
[my fork](https://github.com/tartinesKiller/vue-idb)
